on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./
        id: xchequer
        with:
          log: 'test.log'